subscriptionId: "ad7bd2cc-e664-4f3c-bf8c-1dfad5bb75e4"
managementGroupId: "d0f9b985-0e86-4515-93fe-cfd956836ca5"
vmTagName: "backup"
vmTagValue: "true"
location: "westeurope"
resourceGroupName: "rg-vmbackup-default"
vaultName: "rsv-backup-default"
vaultSkuName: "RS0"
vaultSkuTier: "Standard"
backupPolicyName: "DefaultPolicy"
enableBackup: "true"
backupFrequency: "Daily"
backupRetentionDays: 14
enableAutoRemediation: "false"
createVault: "false"
vaultResourceGroup: "rg-vmbackup-default"